### ISSUE TITLE
Gamma knife

### ISSUE THREAD

**Issue by MohHu** [cerr/CERR#995]
Dear Dr.Apte,

Good morning,

I am writing to you with regard to a gamma knife plan. Actually,  Actually, I would like to extract dose distribution after converting to DICOM  to CERR format. However, I have the following error!

Could i ask you how we can solve it?

Yours sincerely

>> CERR
CERR>>  Scanning DICOM directory
Reading directory:C:\Users\hp\Downloads\TMR10\TMR10 ...
 Reading header ...
CERR>>  DICOM Import has no methods defined for import into the planC{indexS.header}.sponsorID field, leaving empty.
CERR>>  DICOM Import has no methods defined for import into the planC{indexS.header}.protocolID field, leaving empty.
CERR>>  DICOM Import has no methods defined for import into the planC{indexS.header}.subjectID field, leaving empty.
CERR>>  DICOM Import has no methods defined for import into the planC{indexS.header}.submissionID field, leaving empty.
CERR>>  DICOM Import has no methods defined for import into the planC{indexS.header}.timeSaved field, leaving empty.
CERR>>  DICOM Import has no methods defined for import into the planC{indexS.header}.lastSavedInVer field, leaving empty.
CERR>>  DICOM Import has no methods defined for import into the planC{indexS.header}.CERRImportVersion field, leaving empty.
CERR>>  DICOM Import has no methods defined for import into the planC{indexS.header}.anonymizedID field, leaving empty.
 Reading comment ...
 Reading scan ...
Loading Scan ...
 Reading structures ...
Loading RTSTRUCT ...
 Reading structureArray ...
 Reading structureArrayMore ...
 Reading beams ...
 Reading beamGeometry ...
Unrecognized field name "SourceAxisDistance".

Error in getfield (line 69)
        f = f.(field);

Error in populate_planC_beamGeometry_field (line 76)
    beamGeometryInitS(1,i).nominalIsocenterDistance = getfield(beamsInitS, 'BeamSequence',['Item_', num2str(i)],'SourceAxisDistance');

Error in populate_planC_field (line 514)
            beamGeometryS = populate_planC_beamGeometry_field(rtPlans(i), dataS);

Error in dcmdir2planC (line 53)
    cellData = populate_planC_field(cellNames{i}, dcmdir_PATIENT, optS);

Error in CERRImportDCM4CHE (line 120)
    planC = dcmdir2planC(combinedDcmdirS,mergeScansFlag,optS);

Error in CERR (line 133)
                    CERRImportDCM4CHE;
 
Error while evaluating UIControl Callback.

**Comment by MohHu** [comment]
Further to the question above, I tried both the “GammaKnife” option under CERR import, but I have this error. Also exported gamma knife plan to DICOM and import it from DICOM to CERR was also tried, but it is still not working!
Reading MR scan info...
Dot indexing is not supported for variables of this type.

Error in importLeksellPlan (line 168)
for i=1:length(LekC.volS)

Error in CERRImportGammaKnife (line 38)
[planC, leksellInfo] = importLeksellPlan(planDir);

Error in CERR (line 139)
                    CERRImportGammaKnife;
 
Error while evaluating UIControl Callback.

**Comment by adityaapte** [comment]
I just pushed a fix to check for the existence of the SourceAxisDistance
field. Can you please the latest updates and test.

Thanks.

**Comment by MohHu** [comment]
Thank you for your effort. I still have the following error!
>> CERR
Dot indexing is not supported for variables of this type.

Error in importLeksellPlan (line 168)
for i=1:length(LekC.volS)

Error in CERRImportGammaKnife (line 38)
[planC, leksellInfo] = importLeksellPlan(planDir);

Error in CERR (line 139)
                    CERRImportGammaKnife;
 
Error while evaluating UIControl Callback.
